### ISSUE TITLE
Unable to find valid readme

### ISSUE THREAD

**Issue by jamesponddotco** [sindresorhus/awesome-lint#178]
I'm probably missing something obvious, but for some reason I keep getting this error when running the linter:

> [/tmp/awesome-lint][main] ./cli.js https://github.com/jamesponddotco/awesome-privacy-front-ends
> ✖ Unable to find valid readme for "https://github.com/jamesponddotco/awesome-privacy-front-ends"

If you look at the repository, you'll see that the _README.md_ file is indeed there and the `#readme` link works. I am not sure what the issue is.

Could someone shine some light into this issue, please? I would like to use the linter to check for further issues in the repository before opening a pull request on [sindresorhus/awesome](https://github.com/sindresorhus/awesome).

**Comment by bgaillard** [comment]
Hello, I encounter the same problem with https://github.com/bgaillard/readonly.nvim Github repository. 

Last version returns that it does not find the readme file even if I have a `README.md` file.

![image](https://github.com/sindresorhus/awesome-lint/assets/1327782/df0ca1a2-4b05-4e2f-b11e-786459151911)

If I use the previous version `0.18.6` it works.

![image](https://github.com/sindresorhus/awesome-lint/assets/1327782/6f0ad4df-e0ec-4cea-a790-0e7293293381)

I did not write Node.js code since a long time but tried to debug it, the problems seems to be inside the `index.js` file on the call to the `gitClone` method (https://github.com/sindresorhus/awesome-lint/blob/main/index.js#L70).

Neovim gives me the following warning when I open the file.

![image](https://github.com/sindresorhus/awesome-lint/assets/1327782/be62ca4b-12df-4485-a1cc-1ded046f8ce6)

If I add a blocking sleep after the call to `gitClone` it works. 

The problem is that the `git-clone` library provides 2 methods, a sync one and an async one, we have to use the asycn one.

The following PR fixes it I think https://github.com/sindresorhus/awesome-lint/pull/179

**Comment by bgaillard** [comment]
Thanks @sindresorhus :+1:

**Comment by jamesponddotco** [comment]
Thanks, @sindresorhus!
