### ISSUE TITLE
newline after dash okay?

### ISSUE THREAD

**Issue by nschloe** [sindresorhus/awesome-lint#31]
With `awesome-lint` from master, I'm getting
```
✖   21:39  List item link and description separated by invalid whitespace  awesome/list-item
```
with entries like
```
- [BLAS](https://www.netlib.org/blas/) -
  Standard building blocks for performing basic vector and matrix operations.
  (Fortran, public domain)
```
Apparently one needs a whitespace after the dash `-`, not a newline. Too strict?

(Also, it appears that the two files in `./lib` will need to included in the installation as well.)

**Comment by transitive-bullshit** [comment]
Thanks for the heads up @nschloe -- just opened #32 which adds `lib` to `files`.

II don't think we want to support a newline after dash, because in markdown terms, the text is no longer part of the list item. My recommendation would be to remove the newline(s) and try to keep the descriptions short / concise.
