### ISSUE TITLE
Linter is no finding the license section

### ISSUE THREAD

**Issue by glauberfc** [sindresorhus/awesome-lint#79]
I'm receiving the error **License was not detected by GitHub** on [Awesome-React-Hooks](https://github.com/glauberfc/awesome-react-hooks) repo, but it has the `License` section.

**Comment by transitive-bullshit** [comment]
I can confirm this looks like a false negative introduced in #73, specifically these [lines](https://github.com/sindresorhus/awesome-lint/blob/master/rules/github.js#L50-L52).

I've checked several canonical awesome lists, and none of them pass this rule in terms of GitHub recognizing the correct license.

My suggestion is that we remove this portion of the rule for now as it's too strict.

Thoughts?

**Comment by itaisteinherz** [comment]
I agree. The rule should raise a warning in this case, and not report an error.

**Comment by notlmn** [comment]
@glauberfc This is not about the "License" section in readme, but the `license` field returned by the GitHub API. You should include a `license` file that GitHub can recognize and respond to in the API response.

**Comment by glauberfc** [comment]
@notlmn I did this before and don't work

**Comment by notlmn** [comment]
You had `license` file ([about seven months ago](https://github.com/glauberfc/awesome-react-hooks/commit/be9b95d1bf163f325fdc089cf4662e03966379c1)) before the `awesome/github` rule was added, which was recently added in #73.

Add the license file again now and test this. And I'd also suggest you to pin `awesome-lint` dependency to `^0.10.0` and manually update for each release testing for new rules in each release, instead of using `*`.

**Comment by glauberfc** [comment]
Sorry, @notlmn. Some days ago I've create a license file, but I didn't send it to the repo. I tested it local, so I've received the error about license. Now I pushed the license file to the repo and it worked. Thanks!
