### ISSUE TITLE
Spellcheck rule

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/awesome-lint#8]
To catch typos and grammar mistakes.

**Comment by wooorm** [comment]
* Are there examples of translated / non-English awesome lists?
* `en-GB`, `en-US`, both? There’s a pretty good one for [the latter with an MIT/BSD-like license](https://github.com/wooorm/dictionaries/tree/master/dictionaries/en_US).
* Unfortunately I don’t know of complete Hunspell implementations in plain-Node, but `atom/node-spellchecker` has C-bindings and should be pretty good, however it doesn’t properly support passing in a custom dictionary, just the ones on the users computer from what I can gather!

**Comment by sindresorhus** [comment]
> Are there examples of translated / non-English awesome lists?

I've seen some in the wild, but none that are vetted. We can assume English for now.

> en-GB, en-US, both? There’s a pretty good one for the latter with an MIT/BSD-like license.

`en_US`. That one looks great.

**Comment by transitive-bullshit** [comment]
[retext-spell](https://github.com/retextjs/retext-spell) seems like it would be the best implementation option, though I would anticipate a lot of errors for common software idioms like `Node.js`, `NLP`, or `foo`.

I'm not sure spell-check should be in scope for this library if one of our goals is to minimize false errors.

One option would be to reconsider adding this later scoped to certain sections with any issues being considered warnings instead of hard errors.

**Comment by sindresorhus** [comment]
I agree. I think we should rather do our own spellchecker with just some commonly misspelled technical words. Like:

- `NodeJS` => `Node.js`
- `StackOverflow` => `Stack Overflow`
- `Javascript` => `JavaScript`
etc
