### ISSUE TITLE
Linter returns confusing errors

### ISSUE THREAD

**Issue by glauberfc** [sindresorhus/awesome-lint#80]
I'm receiving different errors running the linter some times without didn't any change on `README`.

<img width="717" alt="Screen Shot 2019-05-14 at 7 43 04 PM" src="https://user-images.githubusercontent.com/15311858/57737258-5fb3fa00-7681-11e9-8d1c-004c3e8535e8.png">

**Comment by transitive-bullshit** [comment]
This looks related to #50 given that we're doing a best effort to try and detect dead or inaccessible URLs. Aside from the possibility of fluctuations in your connectivity, it's possible the remote host's uptime or response time is also fluctuating.

Our goal is to be as robust as possible against these types of fluctuations, though it will never be possible to be 100% since not even a human testing manually could accurately say whether a given link is fully dead or not.

Please follow-up with your false negative dead URLs in this [issue](https://github.com/transitive-bullshit/check-links/issues/4). Any other thoughts on how to improve the robustness of dead link checking is very welcome.

Thanks! 😄
