### ISSUE TITLE
Broken Link not actually broken

### ISSUE THREAD

**Issue by rishinair21** [sindresorhus/awesome-lint#85]
Lint detects that a link is broken because the site has DDoS protection. Proof attached that the site is not in fact dead
![image](https://user-images.githubusercontent.com/12476523/61541297-63f7ed00-aa0d-11e9-882d-e010cad9fe9d.png)

**Comment by itaisteinherz** [comment]
This is happening to you because Cloudflare returns the `Just a moment...` page with a 503 status code (and responds to HTTP HEAD requests with the same status code), which makes [`check-links`](https://github.com/transitive-bullshit/check-links) conclude that the URL is dead.
I don't think that this is a bug in `awesome-lint` nor any of its dependencies, but rather an issue with Cloudflare's DDoS protection, and so I think you should contact them (and suggest they return correct status codes for HEAD requests). Also, you will soon be able to make `awesome-lint` [ignore parts of the list you're linting](https://github.com/sindresorhus/awesome-lint/pull/78).

**Comment by transitive-bullshit** [comment]
There is definitely a broader issue here with the remark-lint:no-dead-urls rule. See my proposal in #89 to work around it.
